version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chatbot-backend
    ports:
      - "5000:5000"
    volumes:
      - ./chat_logs:/app/chat_logs
      - ./images:/app/images
      - ./.env:/app/.env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chatbot-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./Image_gallery:/app/Image_gallery
      - ./images:/app/images
    depends_on:
      - backend
    restart: unless-stopped
